# Flags for ttf2pt1
TTF2PT1_FLAGS = CFLAGS_SYS="-DWINDOWS"

# Run make in subdirs
all:
	echo "make ttf2pt1 in ttf2pt1/ ..."
	(cd ttf2pt1; $(MAKE) $(MFLAGS) $(MYMAKEFLAGS) $(TTF2PT1_FLAGS) ttf2pt1)

clean:
	echo "make veryclean in ttf2pt1/ ..."
	(cd ttf2pt1; $(MAKE) $(MFLAGS) $(MYMAKEFLAGS) $(TTF2PT1_FLAGS) veryclean)

