# Run make all in subdirs
all:
	echo "make all in ttf2pt1..."
	(cd ttf2pt1; $(MAKE) $(MFLAGS) $(MYMAKEFLAGS) all)

clean:
	echo "make veryclean in ttf2pt1..."
	(cd ttf2pt1; $(MAKE) $(MFLAGS) $(MYMAKEFLAGS) veryclean)
